{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iorder.fullname" . }}-frontend
  labels:
    {{- include "iorder.labels" . | nindent 4 }}
    {{- include "iorder.selectorLabels" (dict "service" "frontend" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.frontend.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ .Values.frontend.loadBalancerPort | default 80 }}
      targetPort: 80
      protocol: TCP
      name: http
      {{- if and .Values.frontend.nodePort (eq (.Values.frontend.serviceType | default "ClusterIP") "NodePort") }}
      nodePort: {{ .Values.frontend.nodePort }}
      {{- end }}
  selector:
    {{- include "iorder.selectorLabels" (dict "service" "frontend" "context" .) | nindent 4 }}
{{- end }}
