{{- if .Values.pdb.enabled }}
{{- if .Values.pdb.apiGateway }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "iorder.fullname" . }}-api-gateway
  labels:
    {{- include "iorder.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.apiGateway.minAvailable }}
  selector:
    matchLabels:
      {{- include "iorder.selectorLabels" (dict "service" "api-gateway" "context" .) | nindent 6 }}
{{- end }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "iorder.fullname" . }}-products-service
  labels:
    {{- include "iorder.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.productsService.minAvailable }}
  selector:
    matchLabels:
      {{- include "iorder.selectorLabels" (dict "service" "products-service" "context" .) | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "iorder.fullname" . }}-auth-service
  labels:
    {{- include "iorder.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.authService.minAvailable }}
  selector:
    matchLabels:
      {{- include "iorder.selectorLabels" (dict "service" "auth-service" "context" .) | nindent 6 }}
{{- end }}
