apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iorder.fullname" . }}-secrets
  labels:
    {{- include "iorder.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | b64enc | quote }}
