{{- if and .Values.redpanda.enabled .Values.redpandaConsole.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iorder.fullname" . }}-redpanda-console
  labels:
    {{- include "iorder.labels" . | nindent 4 }}
    {{- include "iorder.selectorLabels" (dict "service" "redpanda-console" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "iorder.selectorLabels" (dict "service" "redpanda-console" "context" .) | nindent 4 }}
{{- end }}
