{{- if .Values.redpanda.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iorder.fullname" . }}-redpanda
  labels:
    {{- include "iorder.labels" . | nindent 4 }}
    {{- include "iorder.selectorLabels" (dict "service" "redpanda" "context" .) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "iorder.selectorLabels" (dict "service" "redpanda" "context" .) | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "iorder.labels" . | nindent 8 }}
        {{- include "iorder.selectorLabels" (dict "service" "redpanda" "context" .) | nindent 8 }}
    spec:
      containers:
        - name: redpanda
          image: "{{ .Values.redpanda.image.repository }}:{{ .Values.redpanda.image.tag }}"
          imagePullPolicy: {{ .Values.redpanda.image.pullPolicy }}
          command:
            - rpk
            - redpanda
            - start
            - --kafka-addr
            - "internal://0.0.0.0:9092,external://0.0.0.0:{{ .Values.redpanda.kafka.port }}"
            - --advertise-kafka-addr
            - "internal://{{ include "iorder.fullname" . }}-redpanda:9092,external://{{ include "iorder.fullname" . }}-redpanda:{{ .Values.redpanda.kafka.port }}"
            - --schema-registry-addr
            - "0.0.0.0:{{ .Values.redpanda.schemaRegistry.port }}"
            - --pandaproxy-addr
            - "0.0.0.0:{{ .Values.redpanda.restProxy.port }}"
            - --mode
            - dev-container
            - --smp
            - "1"
            - --memory
            - "256M"
            - --default-log-level=warn
          ports:
            - containerPort: {{ .Values.redpanda.kafka.port }}
              protocol: TCP
              name: kafka
            - containerPort: {{ .Values.redpanda.schemaRegistry.port }}
              protocol: TCP
              name: schema-registry
            - containerPort: {{ .Values.redpanda.restProxy.port }}
              protocol: TCP
              name: rest-proxy
          readinessProbe:
            tcpSocket:
              port: {{ .Values.redpanda.kafka.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: {{ .Values.redpanda.kafka.port }}
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          resources:
            {{- toYaml .Values.redpanda.resources | nindent 12 }}
{{- end }}
