{{- if .Values.redpanda.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iorder.fullname" . }}-redpanda
  labels:
    {{- include "iorder.labels" . | nindent 4 }}
    {{- include "iorder.selectorLabels" (dict "service" "redpanda" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redpanda.kafka.port }}
      targetPort: {{ .Values.redpanda.kafka.port }}
      protocol: TCP
      name: kafka
    - port: {{ .Values.redpanda.schemaRegistry.port }}
      targetPort: {{ .Values.redpanda.schemaRegistry.port }}
      protocol: TCP
      name: schema-registry
    - port: {{ .Values.redpanda.restProxy.port }}
      targetPort: {{ .Values.redpanda.restProxy.port }}
      protocol: TCP
      name: rest-proxy
  selector:
    {{- include "iorder.selectorLabels" (dict "service" "redpanda" "context" .) | nindent 4 }}
{{- end }}
