{{- if .Values.productsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iorder.fullname" . }}-products-service
  labels:
    {{- include "iorder.labels" . | nindent 4 }}
    {{- include "iorder.selectorLabels" (dict "service" "products-service" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.productsService.port }}
      targetPort: {{ .Values.productsService.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "iorder.selectorLabels" (dict "service" "products-service" "context" .) | nindent 4 }}
{{- end }}
