apiVersion: v1
kind: Service
metadata:
  name: {{ include "iorder.fullname" . }}-api-gateway
  labels:
    {{- include "iorder.labels" . | nindent 4 }}
    {{- include "iorder.selectorLabels" (dict "service" "api-gateway" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ .Values.apiGateway.port }}
      targetPort: {{ .Values.apiGateway.port }}
      protocol: TCP
      name: http
      {{- if and .Values.apiGateway.nodePort (eq (.Values.apiGateway.serviceType | default "ClusterIP") "NodePort") }}
      nodePort: {{ .Values.apiGateway.nodePort }}
      {{- end }}
  selector:
    {{- include "iorder.selectorLabels" (dict "service" "api-gateway" "context" .) | nindent 4 }}
