{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "iorder.fullname" . }}-postgresql
  labels:
    {{- include "iorder.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgresql.storage.storageClass }}
  storageClassName: {{ .Values.postgresql.storage.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}
{{- end }}
