{{- if eq (include "iorder.postgresqlEnabled" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iorder.fullname" . }}-postgresql
  labels:
    {{- include "iorder.labels" . | nindent 4 }}
    {{- include "iorder.selectorLabels" (dict "service" "postgresql" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
      protocol: TCP
      name: postgresql
  selector:
    {{- include "iorder.selectorLabels" (dict "service" "postgresql" "context" .) | nindent 4 }}
{{- end }}
